main: phase1_2.cpp Evaluator.cpp Evaluator.h StackInterface.h LinkedStack.h ListInterface.h LinkedList.h Node.h PrecondViolatedExcep.o
	g++ -o main phase1_2.cpp Evaluator.cpp Evaluator.h StackInterface.h LinkedStack.h ListInterface.h LinkedList.h Node.h PrecondViolatedExcep.o

PrecondViolatedExcep.o: PrecondViolatedExcep.h PrecondViolatedExcep.cpp
	g++ -c PrecondViolatedExcep.h PrecondViolatedExcep.cpp
